# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_7AA1oqqVQn2lq-Gv652WpLrqZfdpdt3
"""

import pandas
import numpy as np
import matplotlib.pyplot as plt


csvFile = pandas.read_csv('2016-07-11_ipm_data.txt')
print(csvFile)

maxi = np.max(csvFile)
print(maxi)

indmx = np.argmax(csvFile)
print(indmx)

plt.plot(csvFile,'blue')
plt.scatter(indmx,maxi,color='red')
plt.title('Graph')
plt.grid(color='black')
plt.show()