# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w53egYtI6q4R36Xzw5KwK-ZHr0uXJcaz
"""

class test:
    
    def __init__(self, x, y):
        self.x = x
        
        self.y = y
        
        self.n = self.x - self.y
    
    def Print(self):
      print('\n\nNeutrons = ',self.n)

t1=test(x=int(input('Mass number = ')) ,y=int(input('Number of protons = ')))
t1.Print()